name: Build Android ROM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget curl

    - name: Initialize Repo
      run: |
        mkdir -p ~/android14
        cd ~/android14
        repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r74
        repo sync -j4

    - name: Clone Device Tree
      run: |
        git clone https://github.com/almondnguyen/android_device_samsung_grandppltedx.git ~/android14/device/samsung/grandppltedx

    - name: Build ROM
      run: |
        cd ~/android14
        source build/envsetup.sh
        lunch aosp_grandppltedx-userdebug
        make -j4

    - name: Upload ROM
      uses: actions/upload-artifact@v2
      with:
        name: android-rom
        path: ~/android14/out/target/product/grandppltedx/*.zip
